#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the first release of nutz-verify.
#
#   scripts/wizard-first-release.sh
#
# Sets the one CI secret, pushes main, watches the first CI run, rehearses the live tier
# and the release dry run, cuts the tag, and reproduces the published checksums locally.
# Every outward-facing action is gated on a confirmation, and a red CI run stops the
# wizard before the tag: a checksum the Signer will pin must come from a green tree.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

cd "$(dirname "$0")/.."

REPO=nutzwtf/nutz-verify
GH_USER=nutz-dev
TAG=v0.1.0
CONTRACTS_DIR=${NUTZ_CONTRACTS:-../nutz-contracts}
CHAIN_ID_HEX=0x1237                      # 4663

# The git remote is an SSH alias (github-nutz), which gh cannot map to a repository, so
# every gh command is pointed at the repo explicitly.
export GH_REPO=$REPO

# _newest_run WORKFLOW EVENT [BRANCH]: the id of the newest matching run, or nothing.
_newest_run() {
  local args=(run list --workflow "$1" --event "$2" --limit 1 --json databaseId -q '.[0].databaseId')
  [[ -n "${3:-}" ]] && args+=(--branch "$3")
  gh "${args[@]}" 2>/dev/null || true
}

# wait_for_run WORKFLOW EVENT PREVIOUS_ID [BRANCH]: polls until a run newer than
# PREVIOUS_ID appears (GitHub takes a few seconds to queue one), then watches it to the
# end. Returns the run's exit status; the URL is printed either way.
wait_for_run() {
  local workflow="$1" event="$2" previous="$3" branch="${4:-}" id="" i
  printf '  %swaiting for the %s run to be queued%s' "$DIM" "$workflow" "$RESET"
  for i in $(seq 1 36); do
    id=$(_newest_run "$workflow" "$event" "$branch")
    [[ -n "$id" && "$id" != "$previous" ]] && break
    id=""; printf '.'; sleep 5
  done
  printf '\n'
  if [[ -z "$id" ]]; then
    warn "no $workflow run appeared within three minutes; look at the Actions tab"
    open_url "https://github.com/$REPO/actions"
    return 1
  fi
  say "run $id: https://github.com/$REPO/actions/runs/$id"
  if gh run watch "$id" --exit-status --interval 10; then
    printf '  %s✓ %s is green%s\n' "$GREEN" "$workflow" "$RESET"
  else
    warn "$workflow run $id failed"
    gh run view "$id" --log-failed 2>/dev/null | tail -n 40 || true
    open_url "https://github.com/$REPO/actions/runs/$id"
    return 1
  fi
}

banner "nutz-verify: first release ($TAG)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "GitHub identity: act as $GH_USER"
say "Everything below talks to GitHub as $GH_USER, the account that owns $REPO."
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
  note "GITHUB_TOKEN is set in this shell and shadows gh's keyring; ignoring it for this run."
  unset GITHUB_TOKEN
fi
if ! GH_TOKEN=$(gh auth token --user "$GH_USER" 2>/dev/null) || [[ -z "$GH_TOKEN" ]]; then
  warn "gh has no token for $GH_USER."
  step "Run:  gh auth login --user $GH_USER   (browser flow, scopes repo + workflow)"
  pause "Press Enter once that is done"
  GH_TOKEN=$(gh auth token --user "$GH_USER")
fi
export GH_TOKEN
login=$(gh api user -q .login)
if [[ "$login" != "$GH_USER" ]]; then
  warn "gh is acting as '$login', not $GH_USER; stopping."
  exit 1
fi
if [[ "$(gh api "repos/$REPO" -q .permissions.admin)" != "true" ]]; then
  warn "$login is not an admin on $REPO, so it cannot set secrets; stopping."
  exit 1
fi
say "✓ acting as $login, admin on $REPO"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "RPC_4663: the second, independent chain 4663 endpoint"
say "The nightly live tier compares the public endpoint against this one byte for byte."
say "It is the only test ADR-0002's cross-check has that is not one node compared with itself."
RPC_4663=""
if [[ -f "$CONTRACTS_DIR/.env" ]] && sibling=$(grep -E '^RPC_4663=' "$CONTRACTS_DIR/.env" | tail -n1); then
  sibling=${sibling#*=}
  host=$(printf '%s' "$sibling" | sed -E 's#^https?://([^/]+).*#\1#')
  note "nutz-contracts' CI already uses one, and its checkout has it: host $host"
  if confirm "Use that same endpoint here?"; then RPC_4663=$sibling; fi
fi
if [[ -z "$RPC_4663" ]]; then
  open_url "https://console.chainstack.com/"
  step "Open the chain 4663 (Robinhood) node → Access and credentials → copy the HTTPS endpoint."
  step "Any independent 4663 provider works; an archive endpoint is only needed for deep history."
  ask_secret RPC_4663 "Paste the endpoint URL:"
fi
if [[ -z "$RPC_4663" ]]; then
  warn "no endpoint given; the live tier will run paging only, without the cross-check."
else
  # Enforce §4's chain id here rather than discovering a wrong endpoint at 05:00 UTC.
  got=$(curl -sS --max-time 15 -H 'content-type: application/json' \
        -d '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' "$RPC_4663" \
        | sed -E 's/.*"result":"([^"]+)".*/\1/' || true)
  if [[ "$got" == "$CHAIN_ID_HEX" ]]; then
    say "✓ endpoint answers eth_chainId = $got (4663)"
  else
    warn "endpoint answered eth_chainId '$got', expected $CHAIN_ID_HEX (4663)"
    confirm "Set it anyway?" || exit 1
  fi
  write_env NUTZ_VERIFY_LIVE_RPC_2 "$RPC_4663"     # what internal/chain's live test reads
  set_secret RPC_4663 "$RPC_4663"                  # what ci.yml maps onto it
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Push main, and watch the first CI run"
git fetch -q origin
ahead=$(git rev-list --count origin/main..main)
if [[ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]]; then
  warn "not on main; stopping."; exit 1
fi
if [[ -n "$(git status --porcelain)" ]]; then
  warn "the working tree is not clean; commit or stash first."; exit 1
fi
if (( ahead == 0 )); then
  say "origin/main already has everything."
else
  say "main is $ahead commit(s) ahead of origin/main:"
  git log --oneline origin/main..main | sed 's/^/    /'
  say ""
  say "No CI run has ever happened on GitHub. This push is the first, and the fork of 4663"
  say "the harness needs runs against the public endpoint with no secret."
  confirm "Push main to origin?" || exit 1
  before=$(_newest_run ci.yml push main)
  git push origin main
  wait_for_run ci.yml push "$before" main || {
    warn "CI is red on main. Fix it and re-run this wizard; $TAG is not cut on a red tree."
    exit 1
  }
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Rehearse: the live tier, and a release dry run"
say "Two workflow_dispatch runs. ci.yml with the live job (it needs the secret from stage 2),"
say "and release.yml, which on a dispatch builds on two machines and compares checksums but"
say "publishes nothing. Both are running for the first time, and both take several minutes."
if confirm "Dispatch both?"; then
  before_ci=$(_newest_run ci.yml workflow_dispatch)
  before_rel=$(_newest_run release.yml workflow_dispatch)
  gh workflow run ci.yml --ref main
  gh workflow run release.yml --ref main
  ok=1
  wait_for_run ci.yml workflow_dispatch "$before_ci" || ok=0
  wait_for_run release.yml workflow_dispatch "$before_rel" || ok=0
  if (( ! ok )); then
    warn "a rehearsal failed. A red live tier is not necessarily a bug here (the public"
    warn "endpoint throttles); a red release dry run is, and $TAG should wait for it."
    confirm "Continue to the tag anyway?" || exit 1
  fi
else
  SKIPPED+=("rehearsal of the live tier and the release dry run (gh workflow run ci.yml / release.yml)")
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Cut $TAG"
if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
  say "$TAG already exists locally at $(git rev-parse --short "$TAG")."
else
  say "Tagging $(git rev-parse --short HEAD): $(git log -1 --format=%s)"
  say ""
  say "Pushing the tag publishes a GitHub release whose checksums the warm Signer pins."
  say "A release that already exists is never replaced (release.yml), so a mistake here"
  say "means cutting v0.1.1, not re-cutting $TAG."
  confirm "Create the annotated tag $TAG at HEAD?" || exit 1
  git tag -a "$TAG" -m "nutz-verify $TAG"
fi
if gh api "repos/$REPO/git/refs/tags/$TAG" >/dev/null 2>&1; then
  say "$TAG is already on origin."
else
  confirm "Push $TAG to origin? This is the irreversible step." || exit 1
  before=$(_newest_run release.yml push "$TAG")
  git push origin "$TAG"
  wait_for_run release.yml push "$before" "$TAG" || {
    warn "the release workflow failed; nothing was published if it failed before 'publish'."
    warn "Inspect the run, fix, and cut the next patch tag."
    exit 1
  }
  open_url "https://github.com/$REPO/releases/tag/$TAG"
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Reproduce the published checksums from this machine"
say "The README tells a stranger to run scripts/build-release.sh at the tag and diff"
say "SHA256SUMS against the release. This is that, from a third machine."
work=$(mktemp -d)
published="$work/SHA256SUMS.published"
if ! curl -fsSL "https://github.com/$REPO/releases/download/$TAG/SHA256SUMS" -o "$published"; then
  warn "could not download the published SHA256SUMS; is the release public yet?"
  SKIPPED+=("reproduce $TAG's checksums: scripts/build-release.sh, then diff against the release's SHA256SUMS")
else
  git -c advice.detachedHead=false worktree add -q "$work/src" "$TAG"
  ( cd "$work/src" && scripts/build-release.sh "$work/dist" )
  if diff "$work/dist/SHA256SUMS" "$published"; then
    printf '  %s✓ MATCH: this machine reproduces every published checksum for %s%s\n' "$GREEN" "$TAG" "$RESET"
    cat "$published" | sed 's/^/    /'
  else
    warn "MISMATCH: the local build differs from the release. See README 'Reproducing a release'."
    SKIPPED+=("diagnose the checksum mismatch on $TAG (toolchain? see scripts/build-release.sh output)")
  fi
  git worktree remove --force "$work/src"
fi
rm -rf "$work"
pause

finish
say "Next: pin one of the published checksums where the warm Signer reads it (README, 'Install')."
